### ISSUE TITLE
BERT: Why can't the final block be 1024 bytes?

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#116]
https://www.ietf.org/mail-archive/web/core/current/msg08355.html - WGLC review by Esko Dijk

• Page 22:
   "contain a multiple of 1024 bytes (non-final BERT block) or more than 1024 bytes (final BERT block)"
     -> Why can't the final block be 1024 bytes? I assume a final BERT block of 1024 bytes is allowed; it would be strange to switch back to SZX=6 for that purpose. What about below text ->
   "contain a multiple of 1024 bytes (non-final BERT block) or more than 1023 bytes (final BERT block)"

**Comment by brianraymor** [comment]
@cabo - would you review and validate?

**Comment by cabo** [comment]
The text explains what is allowed with SZX=7 that is not allowed with SZX=6.  As correctly noted, 1024 final is already allowed for SZX=6 (as is 1023, 1022, ...), so this is not explicitly listed in the list of additionally allowed cases.  Maybe make clearer that this extends what has been allowed before instead of just saying that this is now allowed: s/is allowed/is also allowed/.

**Comment by brianraymor** [comment]
That seems like a simpler (if more subtle) edit.
