### ISSUE TITLE
URI Fragment identifiers [RFC7252 erratum]

### ISSUE THREAD

**Issue by ektrah** [core-wg/coap-tcp-tls#124]
[Erratum 4946](https://www.rfc-editor.org/errata_search.php?rfc=7252&eid=4946) is relevant to Section 7.

**Comment by cabo** [comment]
Good point.  So I assume applying the same fix (add »[ "#" fragment ]«) four times to the ABNF in 7.1 to 7.4 would fix that?
(We probably want to line-break before path-abempty in all four cases.)

**Comment by brianraymor** [comment]
If would be helpful to have more context for how the fragment identifier is used in CoAP. I don't see much detail in RFC7252 besides:

`
   Note: Fragments ([RFC3986], Section 3.5) are not part of the request
   URI and thus will not be transmitted in a CoAP request.
`

**Comment by cabo** [comment]
Fragment identifiers are not used in a transfer protocol; their use is a local matter on the client side.  The mistake we made in RFC 7252 is providing ABNF that doesn't show fragment identifiers at all in the URI syntax.  While CoAP as a protocol does not care about them, they are intended to be allowed in CoAP URIs so they can indeed be used on the client side.  The note mentions this, but the ABNF does not reflect that.  Same for coap-tcp-tls.

Does it matter?  The meaning of fragment identifiers is defined by the media type.  So far, there has been little use of fragment identifiers in the media types being used with CoAP.  Now, SenML actually does go ahead and defines a meaning for them, and other media types in the future might as well.  So it would be good if the ABNF in the CoAP standards did not give the impression fragment identifiers cannot be used at all with CoAP URIs.

**Comment by brianraymor** [comment]
_Note from Carsten:_

We may have to reopen that issue based on the about-face that the HTTP WG made here:

> From:
> https://trac.ietf.org/trac/httpbis/changeset/2279
> (Which is now in RFC 7230, which I read as an update to RFC 2616)
> 
> To:
> https://www.ietf.org/mail-archive/web/httpbisa/current/msg24274.html
> https://www.rfc-editor.org/errata_search.php?rfc=7230&eid=4251
> https://mailarchive.ietf.org/arch/msg/apps-discuss/gZVRtgOUFyzOk68FgL1jHTzWG2s
> 
>

**Comment by brianraymor** [comment]
From https://mailarchive.ietf.org/arch/msg/apps-discuss/gZVRtgOUFyzOk68FgL1jHTzWG2s

> > I agree that the fragment is part of the URI; the question, as far as I understand, is whether the *scheme* definition should include the fragment, given the fact that you can attach a fragment to any URI anyway.
> 
> The answer is "no".  http://tools.ietf.org/html/rfc3986#section-4.3

which references:

4.3.  Absolute URI

   Some protocol elements allow only the absolute form of a URI without
   a fragment identifier.  For example, defining a base URI for later
   use by relative references calls for an absolute-URI syntax rule that
   does not allow a fragment.

      absolute-URI  = scheme ":" hier-part [ "?" query ]

   URI scheme specifications must define their own syntax so that all
   strings matching their scheme-specific syntax will also match the
   <absolute-URI> grammar.  Scheme specifications will not define
   fragment identifier syntax or usage, regardless of its applicability
   to resources identifiable via that scheme, as fragment identification
   is orthogonal to scheme definition.  However, scheme specifications
   are encouraged to include a wide range of examples, including
   examples that show use of the scheme's URIs with fragment identifiers
   when such usage is appropriate.

and https://tools.ietf.org/html/rfc7595 further states:


3.  Requirements for Permanent Scheme Definitions

   This section gives considerations for new schemes.  Meeting these
   guidelines is REQUIRED for 'permanent' scheme registration.
   'Permanent' status is appropriate for, but not limited to, use in
   standards.  For URI schemes defined or normatively referenced by IETF
   Standards Track documents, 'permanent' registration status is
   REQUIRED.

   [RFC3986] defines the overall syntax for URIs as:

               URI = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

   A scheme definition cannot override the overall syntax for URIs.  For
   example, this means that fragment identifiers cannot be reused
   outside the generic syntax restrictions and that fragment identifiers
   are not scheme specific.  A scheme definition must specify the scheme
   name and the syntax of the scheme-specific part, which is clarified
   as follows:

                 URI = scheme ":" scheme-specific-part [ "#" fragment ]

                 scheme-specific-part = hier-part [ "?" query ]
