### ISSUE TITLE
RFC 7925 is good for constrained-to-cloud, but not for the other use cases

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#145]
The recommendations in the document (in 7925 Section 4.2, 4.3) are good for CoAP over TCP/TLS in the constrained-to-cloud use case.
For backend interfacing, and in particular for the WebSockets case, you would use what you have in those environments.

**Comment by hannestschofenig** [comment]
Is that true? The WebSocket use case was about browser to IoT device and I believe RFC 7925 is also applicable as well and the doc even talks about that case. 

Where RFC 7525 may be applicable is in the context of gateways-to-cloud. I am not sure that's a realistic use case though since why not use HTTP there right away.

**Comment by cabo** [comment]
@hannestschofenig: The WebSocket case is about the browser to proxy hop, which might (read: will) have different cipher suites available to it than the proxy to Thing hop.

**Comment by cabo** [comment]
EKR advises:

```
Fair enough. I think the key thing is that it be clear. within that, you have several options:

- Inherit the 7295 MTIs
- Inherit the TLS MTIs
- Define your own MTIs.

I tend to think that the first is kind of unwise in this setting, but ultimately it's a WG decision. It does, however, need to be clear.
```

(s/7295/7925/)

**Comment by brianraymor** [comment]
@cabo - do you want to assign to EKR for review or close based on your earlier PR since there has been no further concerns raised by the WG?

**Comment by cabo** [comment]
For now, I think a good look from Hannes will help making sure that we do the right thing here.

**Comment by brianraymor** [comment]
@hannestschofenig - please review and comment before 8/28.

**Comment by hannestschofenig** [comment]
What about this text proposal: 

FROM: 

8.1.  TLS binding for CoAP over TCP

   The TLS usage guidance in [RFC7925] applies, including the guidance
   about cipher suites in that document that are derived from the
   mandatory to implement (MTI) cipher suites defined in [RFC7252].
   (Note that this selection caters for the device-to-cloud use case of
   CoAP over TLS more than for any use within a back-end environment,
   where the standard TLS 1.2 cipher suites or the more recent ones
   defined in [RFC7525] are more appropriate.)
   
TO: 

8.1.  TLS binding for CoAP over TCP

   The TLS usage guidance in [RFC7925] applies to the use of CoAP over TCP/TLS 
   when it is implemented on constrained devices, including the guidance
   about ciphersuites in that document that are derived from the
   mandatory to implement (MTI) ciphersuites defined in [RFC7252].
   
   CoAP over TCP/TLS has, however, a wider applicability. It may, for example, 
   be implemented on a gateway or on a device that is not constrained (like 
   a smart phone or a tablet). In this case, the guidance in RFC 7925 is
   not appropriate and the recommendations in [RFC7525] is appropriate.  
   
   Since the guidance offered in [RFC7925] and [RFC7525] differs in terms of 
   algorithms, and credential types it is assumed that the CoAP over TCP/TLS
   server implements the recommendations offered by both specifications 
   if the range of supported devices include constrained and unconstrained 
   devices.
