### ISSUE TITLE
BERT capability is indicated by CSM Block & Max-Message-Size > 1152, not SZX

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#147]
This language is now no longer needed:

»In control usage, a BERT option is interpreted in the same way as
the
  equivalent Option with SZX == 6, except that it also indicates the
  capability to process BERT blocks.«

We should decide whether we expect BERT implementors to ever use SZX==7 in control usage.
(It might still be handy in a non-connection-oriented transport with large messages, but is redundant here.)

**Comment by hannestschofenig** [comment]
Re-reading the paragraph I don't understand anymore what BERT in control usage means

**Comment by brianraymor** [comment]
@hannestschofenig - _control usage_ is defined / referenced multiple times in the [Block-Wise RFC](https://tools.ietf.org/html/rfc7959 ). For example:

 
   Where Block1 is present in a request or Block2 in a response (i.e.,
   in that message to the payload of which it pertains) it indicates a
   block-wise transfer and describes how this specific block-wise
   payload forms part of the entire body being transferred ("descriptive
   usage").  **Where it is present in the opposite direction, it provides
   additional control on how that payload will be formed or was
   processed ("control usage").**

@cabo - Are you taking your question _We should decide whether we expect BERT implementors to ever use SZX==7 in control usage._ to the list -or- can we perform the suggested edit and close?

**Comment by smolboarm** [comment]
BERT capability makes no sense under Max-Message-Size=2560 , because under this size it forces us to use 1k maximum block size, to leave some space for options (assuming that Max-Message-Size defines maximum packet length consisting of Options + payload marker + Payload, but without CoAP header).

**Comment by cabo** [comment]
You can implement this minimum in your code if you want.  But options don't have to be 2560–2048 = 512 bytes in size, so 2048-byte BERT messages can still be used with a Max-Message-Size of, say, 2200 bytes, or even 2100 for more reasonable options sizes.  If the options for a message get too large, just send a smaller block.  There is no need that all messages have to use the same block size.

**Comment by smolboarm** [comment]
My concern mostly about max-message-size 1152 as a threshold for switching to BERT. Because with message size <2k - we don't have any benefits of using BERT blocks, they will be always reduced to 1k blocks (equal to SZX=6 block size option).
May be it will be better to increase threshold to some number over 2k and define some minimum space for options explicitly or at least note that "don't forget about space for options, when choosing BERT block size based on max-message-size".
Some of the options potentially could be huge, for example path options. And deciding block size based on options size makes implementations complex.
