### ISSUE TITLE
Allow a peer to rely on the Block-wise Transfer Capability Option

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#153]
We should say that implementations that want to make Block-wise Transfer available to their peers MUST indicate the Block-wise Transfer Capability Option, so the peers can rely on the option being present when Block-wise Transfers are to be used.

**Comment by brianraymor** [comment]
@cabo - You want to change  your original text from sig-02 from a SHOULD to a MUST?

_An implementation that supports block-wise transfers SHOULD indicate the Block-wise Transfer Option._

to something like:

_An implementation wishing to offer block-wise transfer to its peers MUST indicate the Block-wise Transfer Option._

because we don't simply want to require implementations that support block-wise transfer to always offer it.

**Comment by cabo** [comment]
Good point.  I have turned it from a mandate to a factual statement:

```
An implementation
wishing to offer block-wise transfers to its peer therefore needs to indicate the Block-wise Transfer Option.
```
