### ISSUE TITLE
Relationship between Max-Message-Size Capability Option and BERT underspecifed

### ISSUE THREAD

**Issue by hannestschofenig** [core-wg/coap-tcp-tls#177]
Max-Message-Size Capability Option says 

> The sender can use the elective Max-Message-Size Option to indicate
>    the maximum message size in bytes that it can receive.

That's great but gets confusing when the BERT functionality is added. 

Let us assume that a device wants to send a 10 MB file to the server and it wants to use BERT to only transmit chunks of 100KB. BERT has a way to indicate this chunking. Would a server then for example use to indicate that it can only receive files up to a maximum size of, let's say, 20 MB or would the value be used in influence the selection of the chunks used in BERT? In the latter case a more realistic value setting would be 100KB for the  Max-Message-Size. 

What happens if the server sets the maximum message size in the example above to 8MB? Would this mean that the client cannot send the file at all anymore? 

Regardless of what the answer is we need to make it clear what the relationship is with BERT.

**Comment by cabo** [comment]
I'm not sure I understand the reasoning here.
Max-Message-Size is just that — the message size.
Assuming your "chunks" are what RFC 7959 calls blocks, their size would indeed be limited by the Max-Message-Size in BERT mode.
I don't understand how a Max-Message-Size of 8 MB would make it harder to do a 20 MB total block-wise transfer than a Max-Message-Size of 100 KB.
I'm also not clear what needs to be explained about the relationship with BERT — Max-Message-Size and BERT are related because both are about/using messages.

**Comment by hannestschofenig** [comment]
My confusion is whether Max-Message-Size defines the maximum size of the entire transfer (file) size or the maximum size of the RFC 7959 block.

The ambiguity arises when BERT is used since there are suddenly two types of message sizes, the total message size of the entire transfer vs. the message size of each single message (block).

**Comment by brianraymor** [comment]
Is this a dup of #160 ?

**Comment by cabo** [comment]
We certainly could add clarifications that address both #160 and the present issue.
