### ISSUE TITLE
Using the Capability and Settings message for version negotiation

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#20]
We need to decide whether this feature is required. If not, then I don't think that it's useful to include _speculative_ text:

## Using the Capability and Settings message for version negotiation

CoAP is defined in RFC 7252 with a version number of 1.  In contrast
to the message layer for UDP and DTLS, the CoAP over TCP message layer
does not send the version number in each single message.  Instead,
options for the Capability and Settings message can be used to perform
a version negotiation.

At the time of writing, there is no known reason for supporting
version numbers different from 1.  The details of a version
negotiation, once it is actually needed, will depend on the specifics
of the new version(s), so the present specification makes no attempt
to specify these details.  However, Capability and Settings messages
have been specifically designed with a view to supporting such a
potential future need.

**Comment by cabo** [comment]
It is *not* required, because we don't have a version ≠ 1.

(The whole point of the section is actually to explain that it is not required, and it would be misguided to define it now because we don't know what characteristics a new version would have, but that the feature is easily provided using CSM.)

I strongly believe that a standard should provide guidance with respect to its own evolution.  Too often, that information is lost when the standard is completed in its 1.0 version, and when people go about making 2.0 (or 1.1) they make all kinds of stupid mistakes because they simply don't know what evolvability is already built in.

But maybe that material can be moved into an appendix if it is too much out of place here.

**Comment by bsilverajan** [comment]
In previous versions of the WebSockets draft, we defined the WebSocket subprotocol name as "coapv1" during the upgrade handshake and for the last version (now merged), the WebSocket subprotocol name has been altered to simply "coap", for the same reasons, ie, there's no good reason to consider other versions.

If we keep the above section on CSM and versioning into the main body, I think it would be a good idea to consider if and how harmonising can be done with the text talking about CoAP versions for WebSockets in the following sections:

- [Section 4.1](https://core-wg.github.io/coap-tcp-tls/#rfc.section.4.1) : "Any later, incompatible versions of CoAP or CoAP over WebSockets will use a different subprotocol name."

- [Section 4.2](https://core-wg.github.io/coap-tcp-tls/#rfc.section.4.2) : "Furthermore, since the CoAP version is already negotiated during the opening handshake, the “Ver” field can be elided as well."

Alternatively, the text in Section 4.2 can simply be amended to mention no version negotiation is performed during the upgrade handshake, and therefore the field is elided.

**Comment by brianraymor** [comment]
Until there's broader discussion, I have retained the CSM section on version negotiation. In my private branch, I've previously updated the section related to _the “Ver” field can be elided as well"_ to reference the CSM speculative section.

**Comment by brianraymor** [comment]
Addressed in #39
