### ISSUE TITLE
Simplifying "CoAP over *"

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#22]
I'm finding "CoAP over **protocol**" to be too verbose - especially in text that references or compares multiple protocol bindings. Can we agree on a shorthand?

- CoAP **_protocol_** such as CoAP UDP, CoAP TCP/TLS, CoAP WebSockets
- CoAP+**_protocol_** such as CoAP+UDP, CoAP+TCP/TLS, CoAP+WebSockets

**Comment by bsilverajan** [comment]
The URI scheme component provides a reasonably good shorthand form to reflect the protocol bindings and the "Terminology" section could perhaps reflect that? It would be approximately lead to something like the following text:

In this document, references to the various transport bindings for conveying CoAP messages adopt the following abbreviations:

- CoAP+TCP refers to CoAP over TCP, and CoAP+WS refers to CoAP over WebSockets. Using "CoAPS+" instead of "CoAP+" implies the use of their corresponding TLS-based secure counterparts.
- CoAP and CoAPS refer to CoAP over UDP and CoAP over DTLS, respectively.
