### ISSUE TITLE
3.5.  Closing the Connection / cancel only on the client side?

### ISSUE THREAD

**Issue by boaks** [core-wg/coap-tcp-tls#80]
3.5.  Closing the Connection
```
All requests for which the CoAP client has not received a response
yet are cancelled when the connection is closed.
```

Does this mean, only the client must cancel the requests?
Or should the server do this also? Then a clarfication may be useful.

**Comment by brianraymor** [comment]
The original - https://tools.ietf.org/html/draft-savolainen-core-coap-websockets-07#section-2.5 - was specific to Observe:
~~~~

   All requests for which the CoAP client has not received a response
   yet are cancelled when the connection is closed.  If the client
   observes one or more resources over the WebSocket Connection, then
   the CoAP server (or intermediary in the role of the CoAP server) MUST
   remove all entries associated with the client from the lists of
   observers when the connection is closed.
~~~~

All updates to Observe are now captured in a single place - Appendix A.  This specific case is in
https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-05#appendix-A.3

At this point, I think that **Closing the Connection** could simply be deleted because there are no specific changes required.

**Comment by ektrah** [comment]
Let's say a client has sent one or more requests to a server but hasn't received any response yet, and/or is observing a resource at a server. If the client or the server closes the connection or if the connection goes down unexpectedly, then the client will never receive the responses or any further notifications. The client has to reconnect and send new requests.

Neither the client nor the server needs to send anything to cancel active requests before closing the connection; when a connection closes, all active requests are canceled automatically. The client should signal that to the code waiting for the responses, e.g., by throwing an exception. The server should abort processing the requests or at least discard the responses once the requests have been processed. The server also should remove the client from the lists of observers (at latest when it tries to send the next notification and it notices that the connection is down).
